spring:
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 2048Mb
  datasource:
    username: ushier
    password: V45q}Zm=Qb
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://ushier.com:3306/hospital_illness?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
mybatis:
  type-aliases-package: com.ushier.stu.hospital-registration.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

